name: Beta Dad
favicon: null
layout_spectrum: 0.513268566224724
typography_spectrum: 0.016286972910165787
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6481711086817086
  lightness: 0.8841434910427779
  saturation: 0.07121147401630878
  rhythmicContrast: 0.23862793622538447
purpose: []
